#include "asm-i386.h"
	TEXT()
	ALIGN(2)
	P2ALIGN(2,3)
GLOBL(C(__builtin_avcall))
	DECLARE_FUNCTION(__builtin_avcall)
FUNBEGIN(__builtin_avcall)
	INSN1(push,l	,R(ebp))
	INSN2(mov,l	,R(esp), R(ebp))
	INSN1(push,l	,R(edi))
	INSN1(push,l	,R(esi))
	INSN2(mov,l	,X4 MEM_DISP(ebp,8), R(edi))
	INSN2(mov,l	,X4 MEM_DISP(edi,20), R(eax))
	INSN2(sub,l	,R(edi), R(eax))
	INSN2(lea,l	,X4 MEM_DISP(eax,-32), R(edx))
	INSN2(sar,l	,NUM(2), R(edx))
	INSN2(xor,l	,R(ecx), R(ecx))
	INSN2(sub,l	,NUM(1024), R(esp))
	INSN2(cmp,l	,R(edx), R(ecx))
	INSN2(mov,l	,R(esp), R(esi))
	INSN1(jge,_	,L(62))
	P2ALIGN(2,3)
L(6:)
	INSN2(mov,l	,X4 MEM_DISP_SHINDEX(edi,32,ecx,4), R(eax))
	INSN2(mov,l	,R(eax), MEM_SHINDEX(esi,ecx,4))
	INSN1(inc,l	,R(ecx))
	INSN2(cmp,l	,R(edx), R(ecx))
	INSN1(jl,_	,L(6))
L(62:)
	INSN2(test,b	,NUM(8), MEM_DISP(edi,4))
	INSN1(je,_	,L(64))
	INSN2(mov,l	,X4 MEM_DISP(edi,12), R(eax))
	INSN2(cmp,l	,NUM(16), R(eax))
	INSN1(je,_	,L(70))
L(7:)
	INSN2(cmp,l	,NUM(13), R(eax))
	INSN1(je,_	,L(71))
	INSN2(cmp,l	,NUM(14), R(eax))
	INSN1(je,_	,L(72))
	INSN1(call,_	,INDIR(MEM(edi)))
	INSN2(mov,l	,X4 MEM_DISP(edi,12), R(esi))
	INSN2(cmp,l	,NUM(1), R(esi))
	INSN2(mov,l	,R(eax), R(ecx))
	INSN1(je,_	,L(9))
	INSN2(test,l	,R(esi), R(esi))
	INSN1(je,_	,L(66))
	INSN2(cmp,l	,NUM(2), R(esi))
	INSN1(je,_	,L(68))
	INSN2(cmp,l	,NUM(3), R(esi))
	INSN1(je,_	,L(68))
	INSN2(cmp,l	,NUM(4), R(esi))
	INSN1(je,_	,L(68))
	INSN2(cmp,l	,NUM(5), R(esi))
	INSN1(je,_	,L(67))
	INSN2(cmp,l	,NUM(6), R(esi))
	INSN1(je,_	,L(67))
	INSN2(cmp,l	,NUM(7), R(esi))
	INSN1(je,_	,L(66))
	INSN2(cmp,l	,NUM(8), R(esi))
	INSN1(je,_	,L(66))
	INSN2(cmp,l	,NUM(9), R(esi))
	INSN1(je,_	,L(66))
	INSN2(cmp,l	,NUM(10), R(esi))
	INSN1(je,_	,L(66))
	INSN2(lea,l	,X4 MEM_DISP(esi,-11), R(eax))
	INSN2(cmp,l	,NUM(1), R(eax))
	INSN1(jbe,_	,L(69))
	INSN2(cmp,l	,NUM(15), R(esi))
	INSN1(je,_	,L(66))
	INSN2(cmp,l	,NUM(16), R(esi))
	INSN1(je,_	,L(73))
	P2ALIGN(2,3)
L(9:)
	INSN2(lea,l	,X4 MEM_DISP(ebp,-8), R(esp))
	INSN1(pop,l	,R(esi))
	INSN2(xor,l	,R(eax), R(eax))
	INSN1(pop,l	,R(edi))
	leave
	ret
L(73:)
	INSN2(mov,l	,X4 MEM_DISP(edi,4), R(eax))
	INSN2(test,l	,NUM(1), R(eax))
	INSN1(je,_	,L(39))
	INSN2(mov,l	,X4 MEM_DISP(edi,16), R(eax))
	INSN2(cmp,l	,NUM(1), R(eax))
	INSN1(je,_	,L(74))
	INSN2(cmp,l	,NUM(2), R(eax))
	INSN1(je,_	,L(75))
	INSN2(cmp,l	,NUM(4), R(eax))
	INSN1(je,_	,L(76))
	INSN2(cmp,l	,NUM(8), R(eax))
	INSN1(je,_	,L(77))
	INSN2(lea,l	,X4 MEM_DISP(eax,3), R(edx))
	INSN2(shr,l	,NUM(2), R(edx))
	INSN1(dec,l	,R(edx))
	INSN1(js,_	,L(9))
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(esi))
L(51:)
	INSN2(mov,l	,X4 MEM_SHINDEX(ecx,edx,4), R(eax))
	INSN2(mov,l	,R(eax), MEM_SHINDEX(esi,edx,4))
	INSN1(dec,l	,R(edx))
	INSN1(jns,_	,L(51))
	INSN1(jmp,_	,L(9))
L(77:)
	INSN2(mov,l	,X4 MEM(ecx), R(edx))
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(eax))
	INSN2(mov,l	,R(edx), MEM(eax))
	INSN2(mov,l	,X4 MEM_DISP(ecx,4), R(edx))
L(65:)
	INSN2(mov,l	,R(edx), MEM_DISP(eax,4))
	INSN1(jmp,_	,L(9))
L(76:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(edx))
	INSN2(mov,l	,X4 MEM(ecx), R(eax))
	INSN2(mov,l	,R(eax), MEM(edx))
	INSN1(jmp,_	,L(9))
L(75:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(edx))
	INSN2(mov,w	,X2 MEM(ecx), R(ax))
	INSN2(mov,w	,R(ax), MEM(edx))
	INSN1(jmp,_	,L(9))
L(74:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(edx))
	INSN2(mov,b	,X1 MEM(ecx), R(al))
	INSN2(mov,b	,R(al), MEM(edx))
	INSN1(jmp,_	,L(9))
	P2ALIGN(2,3)
L(39:)
	INSN2(test,l	,NUM(512), R(eax))
	INSN1(je,_	,L(9))
	INSN2(mov,l	,X4 MEM_DISP(edi,16), R(eax))
	INSN2(cmp,l	,NUM(1), R(eax))
	INSN1(je,_	,L(68))
	INSN2(cmp,l	,NUM(2), R(eax))
	INSN1(je,_	,L(67))
	INSN2(cmp,l	,NUM(4), R(eax))
	INSN1(je,_	,L(66))
	INSN2(cmp,l	,NUM(8), R(eax))
	INSN1(jne,_	,L(9))
L(69:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(eax))
	INSN2(mov,l	,R(ecx), MEM(eax))
	INSN1(jmp,_	,L(65))
	P2ALIGN(2,3)
L(66:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(eax))
	INSN2(mov,l	,R(ecx), MEM(eax))
	INSN1(jmp,_	,L(9))
L(67:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(eax))
	INSN2(mov,w	,R(cx), MEM(eax))
	INSN1(jmp,_	,L(9))
L(68:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(eax))
	INSN2(mov,b	,R(cl), MEM(eax))
	INSN1(jmp,_	,L(9))
L(72:)
	INSN1(call,_	,INDIR(MEM(edi)))
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(eax))
	INSN1(fstp,l	,X8 MEM(eax))
	INSN1(jmp,_	,L(9))
L(71:)
	INSN1(call,_	,INDIR(MEM(edi)))
	INSN2(mov,l	,X4 MEM_DISP(edi,8), R(eax))
	INSN1(fstp,s	,X4 MEM(eax))
	INSN1(jmp,_	,L(9))
L(70:)
	INSN2(mov,l	,X4 MEM_DISP(edi,8),R(ebx))
	INSN1(jmp,_	,L(7))
L(64:)
	INSN2(mov,l	,X4 MEM_DISP(edi,12), R(eax))
	INSN1(jmp,_	,L(7))
L(fe1:)
	FUNEND(__builtin_avcall,L(fe1)-__builtin_avcall)

#if defined __linux__ || defined __FreeBSD__ || defined __FreeBSD_kernel__ || defined __DragonFly__
	.section .note.GNU-stack,"",@progbits
#endif
